This notebook uses the [GapMinder data set](https://www.gapminder.org)

In [1]:
import pandas as pd
data = pd.read_csv("data/gapminder.tsv", sep='\t')
data.head() # show five entries

       country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

Answer the following questions using indexing operations
- Create a table which rows are `country` and columns are `year`. Values are the country's `pop` in that year
- What is the average `pop` per year
- What is the average `pop` per continent

In [2]:
pop2 = data.set_index(['country', 'year'])['pop']
pop2.head()

country      year
Afghanistan  1952     8425333
             1957     9240934
             1962    10267083
             1967    11537966
             1972    13079460
Name: pop, dtype: int64

In [3]:
data2=pop2.unstack('year')
data2.head()

year,1952,1957,1962,1967,1972,1977,1982,1987,1992,1997,2002,2007
country,,,,,,,,,,,,
Afghanistan,8425333,9240934,10267083,11537966,13079460,14880372,12881816,13867957,16317921,22227415,25268405,31889923
Albania,1282697,1476505,1728137,1984060,2263554,2509048,2780097,3075321,3326498,3428038,3508512,3600523
Algeria,9279525,10270856,11000948,12760499,14760787,17152804,20033753,23254956,26298373,29072015,31287142,33333216
Angola,4232095,4561361,4826015,5247469,5894858,6162675,7016384,7874230,8735988,9875024,10866106,12420476
Argentina,17876956,19610538,21283783,22934225,24779799,26983828,29341374,31620918,33958947,36203463,38331121,40301927

In [4]:
data2.mean()

year
1952    1.695040e+07
1957    1.876341e+07
1962    2.042101e+07
1967    2.265830e+07
1972    2.518998e+07
1977    2.767638e+07
1982    3.020730e+07
1987    3.303857e+07
1992    3.599092e+07
1997    3.883947e+07
2002    4.145759e+07
2007    4.402122e+07
dtype: float64

In [5]:
data2.T.mean()

country
Afghanistan           1.582372e+07
Albania               2.580249e+06
Algeria               1.987541e+07
Angola                7.309390e+06
Argentina             2.860224e+07
                          ...
Vietnam               5.456857e+07
West Bank and Gaza    1.848606e+06
Yemen, Rep.           1.084319e+07
Zambia                6.353805e+06
Zimbabwe              7.641966e+06
Length: 142, dtype: float64

In [6]:
# change the default formatting of pandas numbers to avoid scientific formatting
pd.options.display.float_format = lambda x: '{0:.2f}'.format(x)

In [7]:
data2.mean()

year
1952   16950402.46
1957   18763412.54
1962   20421006.86
1967   22658298.48
1972   25189979.99
1977   27676378.92
1982   30207301.69
1987   33038573.37
1992   35990917.32
1997   38839468.11
2002   41457588.58
2007   44021219.57
dtype: float64

In [8]:
data2.T.mean()

country
Afghanistan          15823715.42
Albania               2580249.17
Algeria              19875406.17
Angola                7309390.08
Argentina            28602239.92
                         ...
Vietnam              54568570.92
West Bank and Gaza    1848606.50
Yemen, Rep.          10843191.83
Zambia                6353804.83
Zimbabwe              7641966.08
Length: 142, dtype: float64