In [1]:
import requests
import pandas as pd
import json

# How many code repositories does `hanisaf` own?

Use the API endpoint https://api.github.com/users/:owner/repos

Replace :owner with username (i.e., hanisaf)

In [2]:
username = "hanisaf"
endpoint = f"https://api.github.com/users/{username}/repos"

response = requests.get(endpoint)
if response.status_code == 200:
    data = response.json()
    repos = len(data)
repos

30

In [3]:
data

[{'id': 88653274,
  'node_id': 'MDEwOlJlcG9zaXRvcnk4ODY1MzI3NA==',
  'name': '4TU-CSS',
  'full_name': 'hanisaf/4TU-CSS',
  'private': False,
  'owner': {'login': 'hanisaf',
   'id': 7343838,
   'node_id': 'MDQ6VXNlcjczNDM4Mzg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/7343838?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/hanisaf',
   'html_url': 'https://github.com/hanisaf',
   'followers_url': 'https://api.github.com/users/hanisaf/followers',
   'following_url': 'https://api.github.com/users/hanisaf/following{/other_user}',
   'gists_url': 'https://api.github.com/users/hanisaf/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/hanisaf/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/hanisaf/subscriptions',
   'organizations_url': 'https://api.github.com/users/hanisaf/orgs',
   'repos_url': 'https://api.github.com/users/hanisaf/repos',
   'events_url': 'https://api.github.com/users/hanisaf/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/hanisaf/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'html_url': 'https://github.com/hanisaf/4TU-CSS',
  'description': 'Material for a Computational Social Science (CSS) Workshop hosted by the four Dutch technical universities.',
  'fork': True,
  'url': 'https://api.github.com/repos/hanisaf/4TU-CSS',
  'forks_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/forks',
  'keys_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/keys{/key_id}',
  'collaborators_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/collaborators{/collaborator}',
  'teams_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/teams',
  'hooks_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/hooks',
  'issue_events_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/issues/events{/number}',
  'events_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/events',
  'assignees_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/assignees{/user}',
  'branches_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/branches{/branch}',
  'tags_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/tags',
  'blobs_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/git/blobs{/sha}',
  'git_tags_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/git/tags{/sha}',
  'git_refs_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/git/refs{/sha}',
  'trees_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/git/trees{/sha}',
  'statuses_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/statuses/{sha}',
  'languages_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/languages',
  'stargazers_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/stargazers',
  'contributors_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/contributors',
  'subscribers_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/subscribers',
  'subscription_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/subscription',
  'commits_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/commits{/sha}',
  'git_commits_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/git/commits{/sha}',
  'comments_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/comments{/number}',
  'issue_comment_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/issues/comments{/number}',
  'contents_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/contents/{+path}',
  'compare_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/compare/{base}...{head}',
  'merges_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/merges',
  'archive_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/{archive_format}{/ref}',
  'downloads_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/downloads',
  'issues_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/issues{/number}',
  'pulls_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/pulls{/number}',
  'milestones_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/milestones{/number}',
  'notifications_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/notifications{?since,all,participating}',
  'labels_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/labels{/name}',
  'releases_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/releases{/id}',
  'deployments_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/deployments',
  'created_at': '2017-04-18T17:41:42Z',
  'updated_at': '2017-04-18T17:41:44Z',
  'pushed_at': '2017-04-18T17:43:09Z',
  'git_url': 'git://github.com/hanisaf/4TU-CSS.git',
  'ssh_url': 'git@github.com:hanisaf/4TU-CSS.git',
  'clone_url': 'https://github.com/hanisaf/4TU-CSS.git',
  'svn_url': 'https://github.com/hanisaf/4TU-CSS',
  'homepage': None,
  'size': 17058,
  'stargazers_count': 0,
  'watchers_count': 0,
  'language': 'Jupyter Notebook',
  'has_issues': False,
  'has_projects': True,
  'has_downloads': True,
  'has_wiki': True,
  'has_pages': False,
  'has_discussions': False,
  'forks_count': 0,
  'mirror_url': None,
  'archived': False,
  'disabled': False,
  'open_issues_count': 0,
  'license': None,
  'allow_forking': True,
  'is_template': False,
  'web_commit_signoff_required': False,
  'topics': [],
  'visibility': 'public',
  'forks': 0,
  'open_issues': 0,
  'watchers': 0,
  'default_branch': 'master'},
 {'id': 253311125,
  'node_id': 'MDEwOlJlcG9zaXRvcnkyNTMzMTExMjU=',
  'name': 'advanced-data-management-and-analytics',
  'full_name': 'hanisaf/advanced-data-management-and-analytics',
  'private': False,
  'owner': {'login': 'hanisaf',
   'id': 7343838,
   'node_id': 'MDQ6VXNlcjczNDM4Mzg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/7343838?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/hanisaf',
   'html_url': 'https://github.com/hanisaf',
   'followers_url': 'https://api.github.com/users/hanisaf/followers',
   'following_url': 'https://api.github.com/users/hanisaf/following{/other_user}',
   'gists_url': 'https://api.github.com/users/hanisaf/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/hanisaf/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/hanisaf/subscriptions',
   'organizations_url': 'https://api.github.com/users/hanisaf/orgs',
   'repos_url': 'https://api.github.com/users/hanisaf/repos',
   'events_url': 'https://api.github.com/users/hanisaf/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/hanisaf/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'html_url': 'https://github.com/hanisaf/advanced-data-management-and-analytics',
  'description': 'An online course in advanced data management and analytics',
  'fork': False,
  'url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics',
  'forks_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/forks',
  'keys_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/keys{/key_id}',
  'collaborators_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/collaborators{/collaborator}',
  'teams_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/teams',
  'hooks_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/hooks',
  'issue_events_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/issues/events{/number}',
  'events_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/events',
  'assignees_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/assignees{/user}',
  'branches_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/branches{/branch}',
  'tags_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/tags',
  'blobs_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/git/blobs{/sha}',
  'git_tags_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/git/tags{/sha}',
  'git_refs_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/git/refs{/sha}',
  'trees_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/git/trees{/sha}',
  'statuses_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/statuses/{sha}',
  'languages_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/languages',
  'stargazers_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/stargazers',
  'contributors_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/contributors',
  'subscribers_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/subscribers',
  'subscription_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/subscription',
  'commits_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/commits{/sha}',
  'git_commits_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/git/commits{/sha}',
  'comments_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/comments{/number}',
  'issue_comment_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/issues/comments{/number}',
  'contents_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/contents/{+path}',
  'compare_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/compare/{base}...{head}',
  'merges_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/merges',
  'archive_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/{archive_format}{/ref}',
  'downloads_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/downloads',
  'issues_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/issues{/number}',
  'pulls_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/pulls{/number}',
  'milestones_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/milestones{/number}',
  'notifications_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/notifications{?since,all,participating}',
  'labels_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/labels{/name}',
  'releases_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/releases{/id}',
  'deployments_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/deployments',
  'created_at': '2020-04-05T19:05:27Z',
  'updated_at': '2021-05-04T13:58:45Z',
  'pushed_at': '2021-05-04T13:58:42Z',
  'git_url': 'git://github.com/hanisaf/advanced-data-management-and-analytics.git',
  'ssh_url': 'git@github.com:hanisaf/advanced-data-management-and-analytics.git',
  'clone_url': 'https://github.com/hanisaf/advanced-data-management-and-analytics.git',
  'svn_url': 'https://github.com/hanisaf/advanced-data-management-and-analytics',
  'homepage': '',
  'size': 25475,
  'stargazers_count': 6,
  'watchers_count': 6,
  'language': 'Jupyter Notebook',
  'has_issues': True,
  'has_projects': True,
  'has_downloads': True,
  'has_wiki': True,
  'has_pages': False,
  'has_discussions': False,
  'forks_count': 8,
  'mirror_url': None,
  'archived': False,
  'disabled': False,
  'open_issues_count': 0,
  'license': {'key': 'mit',
   'name': 'MIT License',
   'spdx_id': 'MIT',
   'url': 'https://api.github.com/licenses/mit',
   'node_id': 'MDc6TGljZW5zZTEz'},
  'allow_forking': True,
  'is_template': False,
  'web_commit_signoff_required': False,
  'topics': [],
  'visibility': 'public',
  'forks': 8,
  'open_issues': 0,
  'watchers': 6,
  'default_branch': 'master'},
 {'id': 317369361,
  'node_id': 'MDEwOlJlcG9zaXRvcnkzMTczNjkzNjE=',
  'name': 'advanced-data-management-and-analytics-spring2021',
  'full_name': 'hanisaf/advanced-data-management-and-analytics-spring2021',
  'private': False,
  'owner': {'login': 'hanisaf',
   'id': 7343838,
   'node_id': 'MDQ6VXNlcjczNDM4Mzg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/7343838?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/hanisaf',
   'html_url': 'https://github.com/hanisaf',
   'followers_url': 'https://api.github.com/users/hanisaf/followers',
   'following_url': 'https://api.github.com/users/hanisaf/following{/other_user}',
   'gists_url': 'https://api.github.com/users/hanisaf/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/hanisaf/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/hanisaf/subscriptions',
   'organizations_url': 'https://api.github.com/users/hanisaf/orgs',
   'repos_url': 'https://api.github.com/users/hanisaf/repos',
   'events_url': 'https://api.github.com/users/hanisaf/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/hanisaf/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'html_url': 'https://github.com/hanisaf/advanced-data-management-and-analytics-spring2021',
  'description': "Source code repo for in-class source code and students' package expos",
  'fork': False,
  'url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021',
  'forks_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/forks',
  'keys_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/keys{/key_id}',
  'collaborators_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/collaborators{/collaborator}',
  'teams_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/teams',
  'hooks_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/hooks',
  'issue_events_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/issues/events{/number}',
  'events_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/events',
  'assignees_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/assignees{/user}',
  'branches_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/branches{/branch}',
  'tags_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/tags',
  'blobs_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/git/blobs{/sha}',
  'git_tags_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/git/tags{/sha}',
  'git_refs_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/git/refs{/sha}',
  'trees_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/git/trees{/sha}',
  'statuses_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/statuses/{sha}',
  'languages_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/languages',
  'stargazers_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/stargazers',
  'contributors_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/contributors',
  'subscribers_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/subscribers',
  'subscription_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/subscription',
  'commits_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/commits{/sha}',
  'git_commits_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/git/commits{/sha}',
  'comments_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/comments{/number}',
  'issue_comment_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/issues/comments{/number}',
  'contents_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/contents/{+path}',
  'compare_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/compare/{base}...{head}',
  'merges_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/merges',
  'archive_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/{archive_format}{/ref}',
  'downloads_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/downloads',
  'issues_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/issues{/number}',
  'pulls_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/pulls{/number}',
  'milestones_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/milestones{/number}',
  'notifications_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/notifications{?since,all,participating}',
  'labels_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/labels{/name}',
  'releases_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/releases{/id}',
  'deployments_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021/deployments',
  'created_at': '2020-11-30T23:12:34Z',
  'updated_at': '2021-05-11T20:47:53Z',
  'pushed_at': '2021-05-11T20:47:40Z',
  'git_url': 'git://github.com/hanisaf/advanced-data-management-and-analytics-spring2021.git',
  'ssh_url': 'git@github.com:hanisaf/advanced-data-management-and-analytics-spring2021.git',
  'clone_url': 'https://github.com/hanisaf/advanced-data-management-and-analytics-spring2021.git',
  'svn_url': 'https://github.com/hanisaf/advanced-data-management-and-analytics-spring2021',
  'homepage': None,
  'size': 87395,
  'stargazers_count': 5,
  'watchers_count': 5,
  'language': 'Jupyter Notebook',
  'has_issues': True,
  'has_projects': True,
  'has_downloads': True,
  'has_wiki': True,
  'has_pages': False,
  'has_discussions': False,
  'forks_count': 12,
  'mirror_url': None,
  'archived': False,
  'disabled': False,
  'open_issues_count': 0,
  'license': {'key': 'mit',
   'name': 'MIT License',
   'spdx_id': 'MIT',
   'url': 'https://api.github.com/licenses/mit',
   'node_id': 'MDc6TGljZW5zZTEz'},
  'allow_forking': True,
  'is_template': False,
  'web_commit_signoff_required': False,
  'topics': [],
  'visibility': 'public',
  'forks': 12,
  'open_issues': 0,
  'watchers': 5,
  'default_branch': 'main'},
 {'id': 520247033,
  'node_id': 'R_kgDOHwJW-Q',
  'name': 'aom-2022-content-analysis-pdw',
  'full_name': 'hanisaf/aom-2022-content-analysis-pdw',
  'private': False,
  'owner': {'login': 'hanisaf',
   'id': 7343838,
   'node_id': 'MDQ6VXNlcjczNDM4Mzg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/7343838?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/hanisaf',
   'html_url': 'https://github.com/hanisaf',
   'followers_url': 'https://api.github.com/users/hanisaf/followers',
   'following_url': 'https://api.github.com/users/hanisaf/following{/other_user}',
   'gists_url': 'https://api.github.com/users/hanisaf/gists{/gist_id}',

# Which repositories were created in 2019?

Use the API endpoint https://api.github.com/repos/:owner/:repo

Replace "owner with username and :repo with the repo

In [4]:
repo_names = [d['full_name'] for d in data]

In [5]:
repo_names

['hanisaf/4TU-CSS',
 'hanisaf/advanced-data-management-and-analytics',
 'hanisaf/advanced-data-management-and-analytics-spring2021',
 'hanisaf/aom-2022-content-analysis-pdw',
 'hanisaf/autokeras',
 'hanisaf/bitnami-docker-owncloud',
 'hanisaf/capital_asymmetry_simulation',
 'hanisaf/ChromaDBNavigator',
 'hanisaf/cs-video-courses',
 'hanisaf/Disaster-Response-Pipeline',
 'hanisaf/django-kickstarter-scraper',
 'hanisaf/dscamp_public',
 'hanisaf/enterprise_social_media_simulation_misq',
 'hanisaf/housam-math-challenge',
 'hanisaf/knowledge_gpt',
 'hanisaf/Learning-Racket',
 'hanisaf/mcp_demo',
 'hanisaf/mist4600-spring2019',
 'hanisaf/mist5730-6380-spring2020',
 'hanisaf/mist5730-fall2019',
 'hanisaf/mist6380-summer2019',
 'hanisaf/ODIN',
 'hanisaf/odin-front',
 'hanisaf/odin-site',
 'hanisaf/overview-local',
 'hanisaf/pious-bird-game',
 'hanisaf/preprint',
 'hanisaf/presto',
 'hanisaf/pydata-book',
 'hanisaf/python-bootcamp']

In [6]:
endpoints = [f"https://api.github.com/repos/{r}" for r in repo_names ]

In [7]:
endpoints

['https://api.github.com/repos/hanisaf/4TU-CSS',
 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics',
 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics-spring2021',
 'https://api.github.com/repos/hanisaf/aom-2022-content-analysis-pdw',
 'https://api.github.com/repos/hanisaf/autokeras',
 'https://api.github.com/repos/hanisaf/bitnami-docker-owncloud',
 'https://api.github.com/repos/hanisaf/capital_asymmetry_simulation',
 'https://api.github.com/repos/hanisaf/ChromaDBNavigator',
 'https://api.github.com/repos/hanisaf/cs-video-courses',
 'https://api.github.com/repos/hanisaf/Disaster-Response-Pipeline',
 'https://api.github.com/repos/hanisaf/django-kickstarter-scraper',
 'https://api.github.com/repos/hanisaf/dscamp_public',
 'https://api.github.com/repos/hanisaf/enterprise_social_media_simulation_misq',
 'https://api.github.com/repos/hanisaf/housam-math-challenge',
 'https://api.github.com/repos/hanisaf/knowledge_gpt',
 'https://api.github.com/repos/hanisaf/Learning-Racket',
 'https://api.github.com/repos/hanisaf/mcp_demo',
 'https://api.github.com/repos/hanisaf/mist4600-spring2019',
 'https://api.github.com/repos/hanisaf/mist5730-6380-spring2020',
 'https://api.github.com/repos/hanisaf/mist5730-fall2019',
 'https://api.github.com/repos/hanisaf/mist6380-summer2019',
 'https://api.github.com/repos/hanisaf/ODIN',
 'https://api.github.com/repos/hanisaf/odin-front',
 'https://api.github.com/repos/hanisaf/odin-site',
 'https://api.github.com/repos/hanisaf/overview-local',
 'https://api.github.com/repos/hanisaf/pious-bird-game',
 'https://api.github.com/repos/hanisaf/preprint',
 'https://api.github.com/repos/hanisaf/presto',
 'https://api.github.com/repos/hanisaf/pydata-book',
 'https://api.github.com/repos/hanisaf/python-bootcamp']

In [8]:
repo_data = [requests.get(url).json() for url in endpoints]

In [9]:
repo_data

[{'id': 88653274,
  'node_id': 'MDEwOlJlcG9zaXRvcnk4ODY1MzI3NA==',
  'name': '4TU-CSS',
  'full_name': 'hanisaf/4TU-CSS',
  'private': False,
  'owner': {'login': 'hanisaf',
   'id': 7343838,
   'node_id': 'MDQ6VXNlcjczNDM4Mzg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/7343838?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/hanisaf',
   'html_url': 'https://github.com/hanisaf',
   'followers_url': 'https://api.github.com/users/hanisaf/followers',
   'following_url': 'https://api.github.com/users/hanisaf/following{/other_user}',
   'gists_url': 'https://api.github.com/users/hanisaf/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/hanisaf/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/hanisaf/subscriptions',
   'organizations_url': 'https://api.github.com/users/hanisaf/orgs',
   'repos_url': 'https://api.github.com/users/hanisaf/repos',
   'events_url': 'https://api.github.com/users/hanisaf/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/hanisaf/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'html_url': 'https://github.com/hanisaf/4TU-CSS',
  'description': 'Material for a Computational Social Science (CSS) Workshop hosted by the four Dutch technical universities.',
  'fork': True,
  'url': 'https://api.github.com/repos/hanisaf/4TU-CSS',
  'forks_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/forks',
  'keys_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/keys{/key_id}',
  'collaborators_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/collaborators{/collaborator}',
  'teams_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/teams',
  'hooks_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/hooks',
  'issue_events_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/issues/events{/number}',
  'events_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/events',
  'assignees_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/assignees{/user}',
  'branches_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/branches{/branch}',
  'tags_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/tags',
  'blobs_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/git/blobs{/sha}',
  'git_tags_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/git/tags{/sha}',
  'git_refs_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/git/refs{/sha}',
  'trees_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/git/trees{/sha}',
  'statuses_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/statuses/{sha}',
  'languages_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/languages',
  'stargazers_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/stargazers',
  'contributors_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/contributors',
  'subscribers_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/subscribers',
  'subscription_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/subscription',
  'commits_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/commits{/sha}',
  'git_commits_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/git/commits{/sha}',
  'comments_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/comments{/number}',
  'issue_comment_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/issues/comments{/number}',
  'contents_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/contents/{+path}',
  'compare_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/compare/{base}...{head}',
  'merges_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/merges',
  'archive_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/{archive_format}{/ref}',
  'downloads_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/downloads',
  'issues_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/issues{/number}',
  'pulls_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/pulls{/number}',
  'milestones_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/milestones{/number}',
  'notifications_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/notifications{?since,all,participating}',
  'labels_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/labels{/name}',
  'releases_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/releases{/id}',
  'deployments_url': 'https://api.github.com/repos/hanisaf/4TU-CSS/deployments',
  'created_at': '2017-04-18T17:41:42Z',
  'updated_at': '2017-04-18T17:41:44Z',
  'pushed_at': '2017-04-18T17:43:09Z',
  'git_url': 'git://github.com/hanisaf/4TU-CSS.git',
  'ssh_url': 'git@github.com:hanisaf/4TU-CSS.git',
  'clone_url': 'https://github.com/hanisaf/4TU-CSS.git',
  'svn_url': 'https://github.com/hanisaf/4TU-CSS',
  'homepage': None,
  'size': 17058,
  'stargazers_count': 0,
  'watchers_count': 0,
  'language': 'Jupyter Notebook',
  'has_issues': False,
  'has_projects': True,
  'has_downloads': True,
  'has_wiki': True,
  'has_pages': False,
  'has_discussions': False,
  'forks_count': 0,
  'mirror_url': None,
  'archived': False,
  'disabled': False,
  'open_issues_count': 0,
  'license': None,
  'allow_forking': True,
  'is_template': False,
  'web_commit_signoff_required': False,
  'topics': [],
  'visibility': 'public',
  'forks': 0,
  'open_issues': 0,
  'watchers': 0,
  'default_branch': 'master',
  'temp_clone_token': None,
  'parent': {'id': 81555143,
   'node_id': 'MDEwOlJlcG9zaXRvcnk4MTU1NTE0Mw==',
   'name': '4TU-CSS',
   'full_name': 'vtraag/4TU-CSS',
   'private': False,
   'owner': {'login': 'vtraag',
    'id': 6057804,
    'node_id': 'MDQ6VXNlcjYwNTc4MDQ=',
    'avatar_url': 'https://avatars.githubusercontent.com/u/6057804?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/vtraag',
    'html_url': 'https://github.com/vtraag',
    'followers_url': 'https://api.github.com/users/vtraag/followers',
    'following_url': 'https://api.github.com/users/vtraag/following{/other_user}',
    'gists_url': 'https://api.github.com/users/vtraag/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/vtraag/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/vtraag/subscriptions',
    'organizations_url': 'https://api.github.com/users/vtraag/orgs',
    'repos_url': 'https://api.github.com/users/vtraag/repos',
    'events_url': 'https://api.github.com/users/vtraag/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/vtraag/received_events',
    'type': 'User',
    'user_view_type': 'public',
    'site_admin': False},
   'html_url': 'https://github.com/vtraag/4TU-CSS',
   'description': 'Material for a Computational Social Science (CSS) Workshop hosted by the four Dutch technical universities.',
   'fork': False,
   'url': 'https://api.github.com/repos/vtraag/4TU-CSS',
   'forks_url': 'https://api.github.com/repos/vtraag/4TU-CSS/forks',
   'keys_url': 'https://api.github.com/repos/vtraag/4TU-CSS/keys{/key_id}',
   'collaborators_url': 'https://api.github.com/repos/vtraag/4TU-CSS/collaborators{/collaborator}',
   'teams_url': 'https://api.github.com/repos/vtraag/4TU-CSS/teams',
   'hooks_url': 'https://api.github.com/repos/vtraag/4TU-CSS/hooks',
   'issue_events_url': 'https://api.github.com/repos/vtraag/4TU-CSS/issues/events{/number}',
   'events_url': 'https://api.github.com/repos/vtraag/4TU-CSS/events',
   'assignees_url': 'https://api.github.com/repos/vtraag/4TU-CSS/assignees{/user}',
   'branches_url': 'https://api.github.com/repos/vtraag/4TU-CSS/branches{/branch}',
   'tags_url': 'https://api.github.com/repos/vtraag/4TU-CSS/tags',
   'blobs_url': 'https://api.github.com/repos/vtraag/4TU-CSS/git/blobs{/sha}',
   'git_tags_url': 'https://api.github.com/repos/vtraag/4TU-CSS/git/tags{/sha}',
   'git_refs_url': 'https://api.github.com/repos/vtraag/4TU-CSS/git/refs{/sha}',
   'trees_url': 'https://api.github.com/repos/vtraag/4TU-CSS/git/trees{/sha}',
   'statuses_url': 'https://api.github.com/repos/vtraag/4TU-CSS/statuses/{sha}',
   'languages_url': 'https://api.github.com/repos/vtraag/4TU-CSS/languages',
   'stargazers_url': 'https://api.github.com/repos/vtraag/4TU-CSS/stargazers',
   'contributors_url': 'https://api.github.com/repos/vtraag/4TU-CSS/contributors',
   'subscribers_url': 'https://api.github.com/repos/vtraag/4TU-CSS/subscribers',
   'subscription_url': 'https://api.github.com/repos/vtraag/4TU-CSS/subscription',
   'commits_url': 'https://api.github.com/repos/vtraag/4TU-CSS/commits{/sha}',
   'git_commits_url': 'https://api.github.com/repos/vtraag/4TU-CSS/git/commits{/sha}',
   'comments_url': 'https://api.github.com/repos/vtraag/4TU-CSS/comments{/number}',
   'issue_comment_url': 'https://api.github.com/repos/vtraag/4TU-CSS/issues/comments{/number}',
   'contents_url': 'https://api.github.com/repos/vtraag/4TU-CSS/contents/{+path}',
   'compare_url': 'https://api.github.com/repos/vtraag/4TU-CSS/compare/{base}...{head}',
   'merges_url': 'https://api.github.com/repos/vtraag/4TU-CSS/merges',
   'archive_url': 'https://api.github.com/repos/vtraag/4TU-CSS/{archive_format}{/ref}',
   'downloads_url': 'https://api.github.com/repos/vtraag/4TU-CSS/downloads',
   'issues_url': 'https://api.github.com/repos/vtraag/4TU-CSS/issues{/number}',
   'pulls_url': 'https://api.github.com/repos/vtraag/4TU-CSS/pulls{/number}',
   'milestones_url': 'https://api.github.com/repos/vtraag/4TU-CSS/milestones{/number}',
   'notifications_url': 'https://api.github.com/repos/vtraag/4TU-CSS/notifications{?since,all,participating}',
   'labels_url': 'https://api.github.com/repos/vtraag/4TU-CSS/labels{/name}',
   'releases_url': 'https://api.github.com/repos/vtraag/4TU-CSS/releases{/id}',
   'deployments_url': 'https://api.github.com/repos/vtraag/4TU-CSS/deployments',
   'created_at': '2017-02-10T10:34:19Z',
   'updated_at': '2025-06-11T06:32:37Z',
   'pushed_at': '2023-07-28T13:42:54Z',
   'git_url': 'git://github.com/vtraag/4TU-CSS.git',
   'ssh_url': 'git@github.com:vtraag/4TU-CSS.git',
   'clone_url': 'https://github.com/vtraag/4TU-CSS.git',
   'svn_url': 'https://github.com/vtraag/4TU-CSS',
   'homepage': None,
   'size': 17595,
   'stargazers_count': 81,
   'watchers_count': 81,
   'language': 'Jupyter Notebook',
   'has_issues': True,
   'has_projects': True,
   'has_downloads': True,
   'has_wiki': True,
   'has_pages': True,
   'has_discussions': False,
   'forks_count': 22,
   'mirror_url': None,
   'archived': False,
   'disabled': False,
   'open_issues_count': 0,
   'license': {'key': 'apache-2.0',
    'name': 'Apache License 2.0',
    'spdx_id': 'Apache-2.0',
    'url': 'https://api.github.com/licenses/apache-2.0',
    'node_id': 'MDc6TGljZW5zZTI='},
   'allow_forking': True,
   'is_template': False,
   'web_commit_signoff_required': False,
   'topics': ['workshop'],
   'visibility': 'public',
   'forks': 22,
   'open_issues': 0,
   'watchers': 81,
   'default_branch': 'master'},
  'source': {'id': 81555143,
   'node_id': 'MDEwOlJlcG9zaXRvcnk4MTU1NTE0Mw==',
   'name': '4TU-CSS',
   'full_name': 'vtraag/4TU-CSS',
   'private': False,
   'owner': {'login': 'vtraag',
    'id': 6057804,
    'node_id': 'MDQ6VXNlcjYwNTc4MDQ=',
    'avatar_url': 'https://avatars.githubusercontent.com/u/6057804?v=4',
    'gravatar_id': '',
    'url': 'https://api.github.com/users/vtraag',
    'html_url': 'https://github.com/vtraag',
    'followers_url': 'https://api.github.com/users/vtraag/followers',
    'following_url': 'https://api.github.com/users/vtraag/following{/other_user}',
    'gists_url': 'https://api.github.com/users/vtraag/gists{/gist_id}',
    'starred_url': 'https://api.github.com/users/vtraag/starred{/owner}{/repo}',
    'subscriptions_url': 'https://api.github.com/users/vtraag/subscriptions',
    'organizations_url': 'https://api.github.com/users/vtraag/orgs',
    'repos_url': 'https://api.github.com/users/vtraag/repos',
    'events_url': 'https://api.github.com/users/vtraag/events{/privacy}',
    'received_events_url': 'https://api.github.com/users/vtraag/received_events',
    'type': 'User',
    'user_view_type': 'public',
    'site_admin': False},
   'html_url': 'https://github.com/vtraag/4TU-CSS',
   'description': 'Material for a Computational Social Science (CSS) Workshop hosted by the four Dutch technical universities.',
   'fork': False,
   'url': 'https://api.github.com/repos/vtraag/4TU-CSS',
   'forks_url': 'https://api.github.com/repos/vtraag/4TU-CSS/forks',
   'keys_url': 'https://api.github.com/repos/vtraag/4TU-CSS/keys{/key_id}',
   'collaborators_url': 'https://api.github.com/repos/vtraag/4TU-CSS/collaborators{/collaborator}',
   'teams_url': 'https://api.github.com/repos/vtraag/4TU-CSS/teams',
   'hooks_url': 'https://api.github.com/repos/vtraag/4TU-CSS/hooks',
   'issue_events_url': 'https://api.github.com/repos/vtraag/4TU-CSS/issues/events{/number}',
   'events_url': 'https://api.github.com/repos/vtraag/4TU-CSS/events',
   'assignees_url': 'https://api.github.com/repos/vtraag/4TU-CSS/assignees{/user}',
   'branches_url': 'https://api.github.com/repos/vtraag/4TU-CSS/branches{/branch}',
   'tags_url': 'https://api.github.com/repos/vtraag/4TU-CSS/tags',
   'blobs_url': 'https://api.github.com/repos/vtraag/4TU-CSS/git/blobs{/sha}',
   'git_tags_url': 'https://api.github.com/repos/vtraag/4TU-CSS/git/tags{/sha}',
   'git_refs_url': 'https://api.github.com/repos/vtraag/4TU-CSS/git/refs{/sha}',
   'trees_url': 'https://api.github.com/repos/vtraag/4TU-CSS/git/trees{/sha}',
   'statuses_url': 'https://api.github.com/repos/vtraag/4TU-CSS/statuses/{sha}',
   'languages_url': 'https://api.github.com/repos/vtraag/4TU-CSS/languages',
   'stargazers_url': 'https://api.github.com/repos/vtraag/4TU-CSS/stargazers',
   'contributors_url': 'https://api.github.com/repos/vtraag/4TU-CSS/contributors',
   'subscribers_url': 'https://api.github.com/repos/vtraag/4TU-CSS/subscribers',
   'subscription_url': 'https://api.github.com/repos/vtraag/4TU-CSS/subscription',
   'commits_url': 'https://api.github.com/repos/vtraag/4TU-CSS/commits{/sha}',
   'git_commits_url': 'https://api.github.com/repos/vtraag/4TU-CSS/git/commits{/sha}',
   'comments_url': 'https://api.github.com/repos/vtraag/4TU-CSS/comments{/number}',
   'issue_comment_url': 'https://api.github.com/repos/vtraag/4TU-CSS/issues/comments{/number}',
   'contents_url': 'https://api.github.com/repos/vtraag/4TU-CSS/contents/{+path}',
   'compare_url': 'https://api.github.com/repos/vtraag/4TU-CSS/compare/{base}...{head}',
   'merges_url': 'https://api.github.com/repos/vtraag/4TU-CSS/merges',
   'archive_url': 'https://api.github.com/repos/vtraag/4TU-CSS/{archive_format}{/ref}',
   'downloads_url': 'https://api.github.com/repos/vtraag/4TU-CSS/downloads',
   'issues_url': 'https://api.github.com/repos/vtraag/4TU-CSS/issues{/number}',
   'pulls_url': 'https://api.github.com/repos/vtraag/4TU-CSS/pulls{/number}',
   'milestones_url': 'https://api.github.com/repos/vtraag/4TU-CSS/milestones{/number}',
   'notifications_url': 'https://api.github.com/repos/vtraag/4TU-CSS/notifications{?since,all,participating}',
   'labels_url': 'https://api.github.com/repos/vtraag/4TU-CSS/labels{/name}',
   'releases_url': 'https://api.github.com/repos/vtraag/4TU-CSS/releases{/id}',
   'deployments_url': 'https://api.github.com/repos/vtraag/4TU-CSS/deployments',
   'created_at': '2017-02-10T10:34:19Z',
   'updated_at': '2025-06-11T06:32:37Z',
   'pushed_at': '2023-07-28T13:42:54Z',
   'git_url': 'git://github.com/vtraag/4TU-CSS.git',
   'ssh_url': 'git@github.com:vtraag/4TU-CSS.git',
   'clone_url': 'https://github.com/vtraag/4TU-CSS.git',
   'svn_url': 'https://github.com/vtraag/4TU-CSS',
   'homepage': None,
   'size': 17595,
   'stargazers_count': 81,
   'watchers_count': 81,
   'language': 'Jupyter Notebook',
   'has_issues': True,
   'has_projects': True,
   'has_downloads': True,
   'has_wiki': True,
   'has_pages': True,
   'has_discussions': False,
   'forks_count': 22,
   'mirror_url': None,
   'archived': False,
   'disabled': False,
   'open_issues_count': 0,
   'license': {'key': 'apache-2.0',
    'name': 'Apache License 2.0',
    'spdx_id': 'Apache-2.0',
    'url': 'https://api.github.com/licenses/apache-2.0',
    'node_id': 'MDc6TGljZW5zZTI='},
   'allow_forking': True,
   'is_template': False,
   'web_commit_signoff_required': False,
   'topics': ['workshop'],
   'visibility': 'public',
   'forks': 22,
   'open_issues': 0,
   'watchers': 81,
   'default_branch': 'master'},
  'network_count': 22,
  'subscribers_count': 1},
 {'id': 253311125,
  'node_id': 'MDEwOlJlcG9zaXRvcnkyNTMzMTExMjU=',
  'name': 'advanced-data-management-and-analytics',
  'full_name': 'hanisaf/advanced-data-management-and-analytics',
  'private': False,
  'owner': {'login': 'hanisaf',
   'id': 7343838,
   'node_id': 'MDQ6VXNlcjczNDM4Mzg=',
   'avatar_url': 'https://avatars.githubusercontent.com/u/7343838?v=4',
   'gravatar_id': '',
   'url': 'https://api.github.com/users/hanisaf',
   'html_url': 'https://github.com/hanisaf',
   'followers_url': 'https://api.github.com/users/hanisaf/followers',
   'following_url': 'https://api.github.com/users/hanisaf/following{/other_user}',
   'gists_url': 'https://api.github.com/users/hanisaf/gists{/gist_id}',
   'starred_url': 'https://api.github.com/users/hanisaf/starred{/owner}{/repo}',
   'subscriptions_url': 'https://api.github.com/users/hanisaf/subscriptions',
   'organizations_url': 'https://api.github.com/users/hanisaf/orgs',
   'repos_url': 'https://api.github.com/users/hanisaf/repos',
   'events_url': 'https://api.github.com/users/hanisaf/events{/privacy}',
   'received_events_url': 'https://api.github.com/users/hanisaf/received_events',
   'type': 'User',
   'user_view_type': 'public',
   'site_admin': False},
  'html_url': 'https://github.com/hanisaf/advanced-data-management-and-analytics',
  'description': 'An online course in advanced data management and analytics',
  'fork': False,
  'url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics',
  'forks_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/forks',
  'keys_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/keys{/key_id}',
  'collaborators_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/collaborators{/collaborator}',
  'teams_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/teams',
  'hooks_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/hooks',
  'issue_events_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/issues/events{/number}',
  'events_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/events',
  'assignees_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/assignees{/user}',
  'branches_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/branches{/branch}',
  'tags_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/tags',
  'blobs_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/git/blobs{/sha}',
  'git_tags_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/git/tags{/sha}',
  'git_refs_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/git/refs{/sha}',
  'trees_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/git/trees{/sha}',
  'statuses_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/statuses/{sha}',
  'languages_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/languages',
  'stargazers_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/stargazers',
  'contributors_url': 'https://api.github.com/repos/hanisaf/advanced-data-management-and-analytics/contributors',

In [10]:
created = [(rd['name'], rd['created_at']) for rd in repo_data]

In [11]:
created

[('4TU-CSS', '2017-04-18T17:41:42Z'),
 ('advanced-data-management-and-analytics', '2020-04-05T19:05:27Z'),
 ('advanced-data-management-and-analytics-spring2021', '2020-11-30T23:12:34Z'),
 ('aom-2022-content-analysis-pdw', '2022-08-01T20:02:56Z'),
 ('autokeras', '2018-09-10T14:40:26Z'),
 ('bitnami-docker-owncloud', '2016-06-28T20:17:26Z'),
 ('capital_asymmetry_simulation', '2023-02-18T03:41:38Z'),
 ('ChromaDBNavigator', '2025-08-27T02:26:13Z'),
 ('cs-video-courses', '2022-03-15T11:05:58Z'),
 ('Disaster-Response-Pipeline', '2023-03-16T13:17:53Z'),
 ('django-kickstarter-scraper', '2018-02-04T22:37:30Z'),
 ('dscamp_public', '2021-07-11T14:05:47Z'),
 ('enterprise_social_media_simulation_misq', '2023-02-20T17:49:19Z'),
 ('housam-math-challenge', '2022-06-19T20:30:36Z'),
 ('knowledge_gpt', '2023-05-23T13:24:12Z'),
 ('Learning-Racket', '2017-05-30T01:19:37Z'),
 ('mcp_demo', '2025-08-26T20:41:50Z'),
 ('mist4600-spring2019', '2018-11-30T14:49:18Z'),
 ('mist5730-6380-spring2020', '2020-01-01T12:15:40Z'),
 ('mist5730-fall2019', '2019-08-08T13:19:37Z'),
 ('mist6380-summer2019', '2019-05-10T18:46:01Z'),
 ('ODIN', '2017-04-26T18:33:45Z'),
 ('odin-front', '2018-03-08T18:16:39Z'),
 ('odin-site', '2018-08-20T17:39:17Z'),
 ('overview-local', '2016-10-03T14:14:00Z'),
 ('pious-bird-game', '2025-02-22T16:04:35Z'),
 ('preprint', '2023-02-26T01:48:13Z'),
 ('presto', '2022-06-06T13:45:57Z'),
 ('pydata-book', '2018-09-24T00:06:23Z'),
 ('python-bootcamp', '2018-09-23T22:15:08Z')]

In [12]:
df = pd.DataFrame(created)
df.columns = ['repo', 'creation']
df

                                                 repo              creation
0                                             4TU-CSS  2017-04-18T17:41:42Z
1              advanced-data-management-and-analytics  2020-04-05T19:05:27Z
2   advanced-data-management-and-analytics-spring2021  2020-11-30T23:12:34Z
3                       aom-2022-content-analysis-pdw  2022-08-01T20:02:56Z
4                                           autokeras  2018-09-10T14:40:26Z
5                             bitnami-docker-owncloud  2016-06-28T20:17:26Z
6                        capital_asymmetry_simulation  2023-02-18T03:41:38Z
7                                   ChromaDBNavigator  2025-08-27T02:26:13Z
8                                    cs-video-courses  2022-03-15T11:05:58Z
9                          Disaster-Response-Pipeline  2023-03-16T13:17:53Z
10                         django-kickstarter-scraper  2018-02-04T22:37:30Z
11                                      dscamp_public  2021-07-11T14:05:47Z
12            enterprise_social_media_simulation_misq  2023-02-20T17:49:19Z
13                              housam-math-challenge  2022-06-19T20:30:36Z
14                                      knowledge_gpt  2023-05-23T13:24:12Z
15                                    Learning-Racket  2017-05-30T01:19:37Z
16                                           mcp_demo  2025-08-26T20:41:50Z
17                                mist4600-spring2019  2018-11-30T14:49:18Z
18                           mist5730-6380-spring2020  2020-01-01T12:15:40Z
19                                  mist5730-fall2019  2019-08-08T13:19:37Z
20                                mist6380-summer2019  2019-05-10T18:46:01Z
21                                               ODIN  2017-04-26T18:33:45Z
22                                         odin-front  2018-03-08T18:16:39Z
23                                          odin-site  2018-08-20T17:39:17Z
24                                     overview-local  2016-10-03T14:14:00Z
25                                    pious-bird-game  2025-02-22T16:04:35Z
26                                           preprint  2023-02-26T01:48:13Z
27                                             presto  2022-06-06T13:45:57Z
28                                        pydata-book  2018-09-24T00:06:23Z
29                                    python-bootcamp  2018-09-23T22:15:08Z

In [13]:
df['date'] = pd.to_datetime(df['creation'])
df

,repo,creation,date
0,4TU-CSS,2017-04-18T17:41:42Z,2017-04-18 17:41:42+00:00
1,advanced-data-management-and-analytics,2020-04-05T19:05:27Z,2020-04-05 19:05:27+00:00
2,advanced-data-management-and-analytics-spring2021,2020-11-30T23:12:34Z,2020-11-30 23:12:34+00:00
3,aom-2022-content-analysis-pdw,2022-08-01T20:02:56Z,2022-08-01 20:02:56+00:00
4,autokeras,2018-09-10T14:40:26Z,2018-09-10 14:40:26+00:00
5,bitnami-docker-owncloud,2016-06-28T20:17:26Z,2016-06-28 20:17:26+00:00
6,capital_asymmetry_simulation,2023-02-18T03:41:38Z,2023-02-18 03:41:38+00:00
7,ChromaDBNavigator,2025-08-27T02:26:13Z,2025-08-27 02:26:13+00:00
8,cs-video-courses,2022-03-15T11:05:58Z,2022-03-15 11:05:58+00:00
9,Disaster-Response-Pipeline,2023-03-16T13:17:53Z,2023-03-16 13:17:53+00:00
10,django-kickstarter-scraper,2018-02-04T22:37:30Z,2018-02-04 22:37:30+00:00
11,dscamp_public,2021-07-11T14:05:47Z,2021-07-11 14:05:47+00:00
12,enterprise_social_media_simulation_misq,2023-02-20T17:49:19Z,2023-02-20 17:49:19+00:00
13,housam-math-challenge,2022-06-19T20:30:36Z,2022-06-19 20:30:36+00:00
14,knowledge_gpt,2023-05-23T13:24:12Z,2023-05-23 13:24:12+00:00
15,Learning-Racket,2017-05-30T01:19:37Z,2017-05-30 01:19:37+00:00
16,mcp_demo,2025-08-26T20:41:50Z,2025-08-26 20:41:50+00:00
17,mist4600-spring2019,2018-11-30T14:49:18Z,2018-11-30 14:49:18+00:00
18,mist5730-6380-spring2020,2020-01-01T12:15:40Z,2020-01-01 12:15:40+00:00
19,mist5730-fall2019,2019-08-08T13:19:37Z,2019-08-08 13:19:37+00:00
20,mist6380-summer2019,2019-05-10T18:46:01Z,2019-05-10 18:46:01+00:00
21,ODIN,2017-04-26T18:33:45Z,2017-04-26 18:33:45+00:00
22,odin-front,2018-03-08T18:16:39Z,2018-03-08 18:16:39+00:00
23,odin-site,2018-08-20T17:39:17Z,2018-08-20 17:39:17+00:00
24,overview-local,2016-10-03T14:14:00Z,2016-10-03 14:14:00+00:00
25,pious-bird-game,2025-02-22T16:04:35Z,2025-02-22 16:04:35+00:00
26,preprint,2023-02-26T01:48:13Z,2023-02-26 01:48:13+00:00
27,presto,2022-06-06T13:45:57Z,2022-06-06 13:45:57+00:00
28,pydata-book,2018-09-24T00:06:23Z,2018-09-24 00:06:23+00:00
29,python-bootcamp,2018-09-23T22:15:08Z,2018-09-23 22:15:08+00:00

In [14]:
df['year'] = df['date'].apply(lambda x: x.year)
df

,repo,creation,date,year
0,4TU-CSS,2017-04-18T17:41:42Z,2017-04-18 17:41:42+00:00,2017
1,advanced-data-management-and-analytics,2020-04-05T19:05:27Z,2020-04-05 19:05:27+00:00,2020
2,advanced-data-management-and-analytics-spring2021,2020-11-30T23:12:34Z,2020-11-30 23:12:34+00:00,2020
3,aom-2022-content-analysis-pdw,2022-08-01T20:02:56Z,2022-08-01 20:02:56+00:00,2022
4,autokeras,2018-09-10T14:40:26Z,2018-09-10 14:40:26+00:00,2018
5,bitnami-docker-owncloud,2016-06-28T20:17:26Z,2016-06-28 20:17:26+00:00,2016
6,capital_asymmetry_simulation,2023-02-18T03:41:38Z,2023-02-18 03:41:38+00:00,2023
7,ChromaDBNavigator,2025-08-27T02:26:13Z,2025-08-27 02:26:13+00:00,2025
8,cs-video-courses,2022-03-15T11:05:58Z,2022-03-15 11:05:58+00:00,2022
9,Disaster-Response-Pipeline,2023-03-16T13:17:53Z,2023-03-16 13:17:53+00:00,2023
10,django-kickstarter-scraper,2018-02-04T22:37:30Z,2018-02-04 22:37:30+00:00,2018
11,dscamp_public,2021-07-11T14:05:47Z,2021-07-11 14:05:47+00:00,2021
12,enterprise_social_media_simulation_misq,2023-02-20T17:49:19Z,2023-02-20 17:49:19+00:00,2023
13,housam-math-challenge,2022-06-19T20:30:36Z,2022-06-19 20:30:36+00:00,2022
14,knowledge_gpt,2023-05-23T13:24:12Z,2023-05-23 13:24:12+00:00,2023
15,Learning-Racket,2017-05-30T01:19:37Z,2017-05-30 01:19:37+00:00,2017
16,mcp_demo,2025-08-26T20:41:50Z,2025-08-26 20:41:50+00:00,2025
17,mist4600-spring2019,2018-11-30T14:49:18Z,2018-11-30 14:49:18+00:00,2018
18,mist5730-6380-spring2020,2020-01-01T12:15:40Z,2020-01-01 12:15:40+00:00,2020
19,mist5730-fall2019,2019-08-08T13:19:37Z,2019-08-08 13:19:37+00:00,2019
20,mist6380-summer2019,2019-05-10T18:46:01Z,2019-05-10 18:46:01+00:00,2019
21,ODIN,2017-04-26T18:33:45Z,2017-04-26 18:33:45+00:00,2017
22,odin-front,2018-03-08T18:16:39Z,2018-03-08 18:16:39+00:00,2018
23,odin-site,2018-08-20T17:39:17Z,2018-08-20 17:39:17+00:00,2018
24,overview-local,2016-10-03T14:14:00Z,2016-10-03 14:14:00+00:00,2016
25,pious-bird-game,2025-02-22T16:04:35Z,2025-02-22 16:04:35+00:00,2025
26,preprint,2023-02-26T01:48:13Z,2023-02-26 01:48:13+00:00,2023
27,presto,2022-06-06T13:45:57Z,2022-06-06 13:45:57+00:00,2022
28,pydata-book,2018-09-24T00:06:23Z,2018-09-24 00:06:23+00:00,2018
29,python-bootcamp,2018-09-23T22:15:08Z,2018-09-23 22:15:08+00:00,2018

In [15]:
df[df['year']==2019]

                   repo              creation                      date  year
19    mist5730-fall2019  2019-08-08T13:19:37Z 2019-08-08 13:19:37+00:00  2019
20  mist6380-summer2019  2019-05-10T18:46:01Z 2019-05-10 18:46:01+00:00  2019

In [16]:
df.groupby('year')['repo'].count()

year
2016    2
2017    3
2018    7
2019    2
2020    3
2021    1
2022    4
2023    5
2025    3
Name: repo, dtype: int64